Cloud bastion
Otus-DevOps-2023-03/117thDragon_infra pull request #2
Opened 2023-05-05 09:06 UTC by 117thDragon

2023-05-05 13:22 UTC, mrgreyves requested changes
Здравствуйте!
![image](https://user-images.githubusercontent.com/34331259/236469094-34a6fb3b-da5b-43d1-bb84-90333ff7ba35.png)
Добавляем описание к пр =)

2023-05-05 13:32 UTC, mrgreyves approved these changes
Здравствуйте!
Апрув ^_^

2023-05-05 13:54 UTC, 117thDragon commented
Надеюсь я правильно в этот раз описал задачи?
К сожалению не успеваю иной раз. 
В README.md добавил описание, а так же указал на недочеты.

2023-05-06 08:28 UTC, mrgreyves commented
Здравствуйте!
Да, в этот раз у вас получилось крутое описание =)

2023-05-06 08:29 UTC, 117thDragon commented
Отлично, ранее не разобрался.
Последую ДЗ буду оформлять аналогично.

2023-05-09 09:54 UTC, mrgreyves commented
Здравствуйте!)
Вам нужно помержеть ваш пуллреквест =)

2023-05-09 10:42 UTC, merged